name = "portfolio-api"
compatibility_date = "2024-02-08"
main = "src/index.ts"

[vars]
GITHUB_API_URL = "https://api.github.com"

[observability]
enabled = true

[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio-db"
database_id = "223fa851-ea8e-4e53-b17d-521db010a695"

[[r2_buckets]]
binding = "portfolio_assets"
bucket_name = "portfolio-assets"
